name: WorldWrapper
main: com.teknoserval.worldwrapper.WorldWrapper
version: '1.2.2'
api-version: '1.21'
author: TeknoServal
commands:
  worldwrapper:
    description: options for the worldwrapper plugin
    usage: /worldwrapper []
    permission: WorldWrapper.command
    permission-message: You don't have permission to use this command.